### PR TITLE
Add release note section

### PR DESCRIPTION
**Pull request by kprosise**
Sidebar entry added for `source/release-notes/release-notes.rst`. Template file also added.

This commit will allow review of the format.  
After being merged, content will be added prior to v92.

QA Steps: built and checked html, no issues noted.

This commit addresses FFTK-2537

## Readiness

*   [x] Merge (pending reviews)
*   [ ] Merge after _date or event_
*   [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._  
_You can fill this out after opening the PR. "Did I..."_

*   [x] Run spelling and grammar check, preferably with linter.
*   [x] Avoid changing any header associated with a link/reference.
*   [ ] Step through instructions (or ask someone to do so).
*   [x] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
*   [x] Match tone and style of page/section.
*   [x] Run `make linkcheck`.
*   [x] View HTML in a browser to check rendering.
*   [x] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
*   [x] follow best practices for commits.
    *   [x] Descriptive title written in the imperative.
    *   [x] Include brief overview of QA steps taken.
    *   [x] Mention any related issues numbers.
    *   [x] End message with sign off/DCO line (`-s, --signoff`).
    *   [x] Sign commit with your gpg key (`-S, --gpg-sign`).
    *   [x] Squash commits if needed.
*   [x] Request PR review by a technical writer and at least one peer.

## Comments

This can be seen as a draft, feel free to make suggestions regarding the layout. Actual content will be added prior to next release, but I figured it would be good to establish the template now.

### CODE REVIEW

**Review by ricardosalveti — APPROVED** [review]
Nice, LGTM

**Review by MrCry0 — APPROVED** [review]

**Comment by doanac** [comment]
Docs for 137bf6ca1f52f080f7dd650fb06da1b61958b14e are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2442/docs/artifacts/html/index.html

**Comment by angolini** [comment]
Are we going to duplicate the release note file? or the goal is to have it only here and the be displayed in the other site?

**Comment by ricardosalveti** [comment]
> Are we going to duplicate the release note file? or the goal is to have it only here and the be displayed in the other site?

Not necessarily duplicate it (just the highlights), the idea is to have another location (available via docs) which covers the high level a bit more, besides the migration/updates issues people should be aware of (e.g. when we deprecate something).

Atm we can't have that information easily on our current release notes page.

**Comment by angolini** [comment]
If we are going to have two "different" Release Notes, they must have different names.

I still think we should remove the other one (https://foundries.io/products/releases/91/) and keep only this one (or, display this one in the other link)

**Pull request merged**
