### PR TITLE
secure-boot: clarify the need to update the UUU scripts after fusing

### PR DESCRIPTION
**Pull request by ldts**
Some projects might define a close.uuu script in their
meta-subscriber-overrride to perform further verification before
closing the device. It is unlikely that such a script will be
executing a signed SPL and therefore will not succeed as HAB events
will be triggering on boot.

This commit raises the awareness of the need to update all of the users UUU
scripts once the fuses have been burnt (before even closing the device).

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for ffe84f750f505699b89f8a5cc0f8917569330830 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/386/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for c7521be77971fbf7c1b2268bc0d287749adffd6e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/387/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 25c46349709aff86eb57e694ac7342c940677f17 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/388/docs/artifacts/html/index.html

**Comment by ricardosalveti** [comment]
LGTM

**Pull request merged**
