### PR TITLE
tutorials: Update cmd

### PR DESCRIPTION
**Pull request by angolini**
On the command:
fioctl devices config updates --compose-apps --apps

--compose-apps is an unknown flag

Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 40ca377d67736dd99847baac239ebc12aeba43b9 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/978/docs/artifacts/html/index.html

**Comment by angolini** [comment]
@munoz0raul , could you, please, confirm that the new command line works as expected on your side?

I have tested it over here and for me it looks like it's ok.

I'm working to find the commit where this has changed, when I find I update it here

**Comment by angolini** [comment]
The command has changed in this commit https://github.com/foundriesio/fioctl/commit/25cf9902855c6803eaab538de9858e0a2d61681c#diff-fc4d2aaa175b390a8e189bd388d4ea286d5401c0582aa0102d00ec534190e405L29

**Review by mike-scott — APPROVED** [review]
LGTM

**Comment by munoz0raul** [comment]
LGTM

**Review by munoz0raul — APPROVED** [review]

**Pull request merged**
