### PR TITLE
Refactor improvements 2

### PR DESCRIPTION
**Pull request by MatthewCroughan**
follow up from #103 

Commit messages should be self explanatory as a changelog.

### CODE REVIEW

**Comment by MatthewCroughan** [comment]
ci-rebuild

**Comment by MatthewCroughan** [comment]
ci-retest

**Comment by doanac** [comment]
Docs for 942e92294080f8bb80ff3a0b64bddd4916ffd0ef are browesable at: https://ci.foundries.io/projects/fio-docs/builds/658/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for df472173b7515e3b5a49351fe2f880f60b97ec20 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/659/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 95b66f0e4abbd59cbe49c6f009b3dc8014461719 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/660/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 2e5171e9c4493ca3704eed3fd22694ee1be88b75 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/661/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 499096569cfb15f145263b6dab6e87429087b2f1 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/662/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 664d8a6d5378e8dbd7f9112722707caf49952ded are browesable at: https://ci.foundries.io/projects/fio-docs/builds/663/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 38f7ce9b10f0e4d7ec23cd1c8ee5e46bf81c7119 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/664/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 77127d007e891f28bbb5ceb71406eba58c3a5d00 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/665/docs/artifacts/html/index.html

**Pull request merged**
