### PR TITLE
LMP: Update location of LMP binary artifacts

### PR DESCRIPTION
**Pull request by doanac**
These are now uploaded to GitHub for anyone to use.

Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
This isn't quite ready. I've got a couple of broken links. I'll get this fixed shortly

**Comment by doanac** [comment]
This is a test

**Comment by doanac** [comment]
Docs for 344f2c410ceab691679d9f5a13f001346bcb325f are browesable at: https://ci.foundries.io/projects/fio-docs/builds/269/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 2ffd416efc43896809be2dabe9553e4160c38227 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/271/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Okay - i think this is ready for review now. We probably just need to whitelist the link that linkcheck is failing on.

**Comment by mike-scott** [comment]
Docs have some odd artifact:
https://ci.foundries.io/projects/fio-docs/builds/271/docs/artifacts/html/tutorial/installation-linux.html#install-base-microplatform

**Comment by mike-scott** [comment]
Looks like this is the 37 release link in the docs:
https://github.com/foundriesio/lmp-manifest/releases/download/486/lmp-gateway-image-raspberrypi3-64.img.gz

But I think that's incorrect.  It's supposed to be:
https://github.com/foundriesio/lmp-manifest/releases/download/37/lmp-gateway-image-raspberrypi3-64.img.gz

**Comment by doanac** [comment]
@mike-scott - I think we've always generate the docs like this and they are only accurate when we do *update* CI run which can tell it what number to use. I'm not sure what we can do about that, but I'm open to suggestions.

**Comment by mike-scott** [comment]
Maybe the artifacting I'm seeing is related to missing CSS somewhere?  It's also in the menus and throughout some of the other pages.

**Comment by mike-scott** [comment]
> @mike-scott its basically the same thing. We don't know what the name of the update will be when generating the CI version of the docs so it just puts "latest" in those places.

Ok, makes sense

**Comment by mike-scott** [comment]
> @mike-scott - I think we've always generate the docs like this and they are only accurate when we do _update_ CI run which can tell it what number to use. I'm not sure what we can do about that, but I'm open to suggestions.

Ok, make sense

**Comment by mbolivar** [comment]
LGTM, thanks

**Comment by mbolivar** [comment]
```
Warning, treated as error:
/repo/source/tutorial/installation-linux.rst.rst:60:broken link: https://github.com/foundriesio/lmp-manifest/releases/download/486/lmp-gateway-image-raspberrypi3-64.img.gz (404 Client Error: Not Found for url: https://github.com/foundriesio/lmp-manifest/releases/download/486/lmp-gateway-image-raspberrypi3-64.img.gz)
make: *** [Makefile:49: linkcheck] Error 2
```

Any idea about this one?

**Comment by mbolivar** [comment]
> We probably just need to whitelist the link that linkcheck is failing on.

Seems reasonable

**Comment by doanac** [comment]
Docs for be9d1798536ebd1f270c18971a9cfd81a8b69199 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/272/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for e4181e0ffc52b8c921ac2d826ffff20289c6754c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/274/docs/artifacts/html/index.html

**Pull request merged**
