### PR TITLE
Postfix -secureboot to qemuarm64

### PR DESCRIPTION
**Pull request by kprosise**
Files in reference-manual changed, including the demo. QA was not able
to be completed as wic artifact does not show change, and flash.bin is
missing. Documentation build and changes were verified.

This applies to FFTK-1106

Signed-off-by: Katrina Prosise <katrina.prosise@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for b4816e3297ec0862334ba5530f9de0d36727bfa9 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1223/docs/artifacts/html/index.html

**Comment by vanmaegima** [comment]
@kprosise we still have an occurrence of qemuarm64 in https://ci.foundries.io/projects/fio-docs/builds/1223/docs/artifacts/html/reference-manual/linux/linux-supported.html
Or are you waiting for this to be in place on the boards drop-down list first?

**Comment by kprosise** [comment]
> @kprosise we still have an occurrence of qemuarm64 in https://ci.foundries.io/projects/fio-docs/builds/1223/docs/artifacts/html/reference-manual/linux/linux-supported.html Or are you waiting for this to be in place on the boards drop-down list first?

I'm thinking we should wait until it is on the drop-down, but no, that occurrence is an oversight on my end, I saw it when I ran grep, but then forgot. I can do a fixup

**Comment by mike-scott** [comment]
Getting the drop down commit ready.

**Comment by doanac** [comment]
Docs for b5e6a50c53a2b759abd4518fd51ed468478abaf4 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1224/docs/artifacts/html/index.html

**Comment by vanmaegima** [comment]
LGTM, but the patches seem duplicated. Could you please verify? It would be good to drop the merge commit as well.

**Comment by doanac** [comment]
Docs for eb4032b94ee2c93c803def357d8772f8575bb36a are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1227/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
> LGTM, but the patches seem duplicated. Could you please verify? It would be good to drop the merge commit as well.

My git was a bit rusty. Dropped the duplicate and the merge commit.

**Review by vanmaegima — APPROVED** [review]
LGTM, thanks!!

**Pull request merged**
