### PR TITLE
FF-76: add section about creating a factory

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**
Add a brief section about the benefits of creating your own factory.

Signed-off-by: Tyler Baker <tyler@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 405c5e35798d1d5eff292bfb23ced17510e5425f are browesable at: https://ci.foundries.io/projects/fio-docs/builds/307/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 6632ee8a8647bb5447e19ad9c7e1c74352954481 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/308/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 95ff2497ad5d6f9a7c8ca251c95f3868153e121d are browesable at: https://ci.foundries.io/projects/fio-docs/builds/309/docs/artifacts/html/index.html

**Comment by EmbeddedAndroid** [comment]
ci-retest

**Comment by doanac** [comment]
Docs for 333523351afac3f99afed75ed02ad3d4a611d429 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/313/docs/artifacts/html/index.html

**Pull request merged**
