### PR TITLE
se050: importing secure objects

### PR DESCRIPTION
**Pull request by ldts**
succintly inform of the secure object import design

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 73305b1cbd22dbcca9d0ba758423d222f42b303f are browesable at: https://ci.foundries.io/projects/fio-docs/builds/689/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 76f77ef4d82af6237b268f8f4f0466aabf2692d4 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/690/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for a325bded60cdfd747edfff13ff0b10276d788f90 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/691/docs/artifacts/html/index.html

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
@MatthewCroughan mind doing a quick review?

**Comment by MatthewCroughan** [comment]
There's a small issue here, where the `The` wraps around the edge of the image. Looking into that now.
image

**Comment by ldts** [comment]
I don't see that problem....is it fixed?

**Review by MatthewCroughan — APPROVED** [review]
@ldts Yes. That is really odd.. The issue seems to not exist anymore. Must have been my browser having a bad day, so many spurious things have happened since I joined Foundries, are computers really deterministic? :smile:

**Comment by ldts** [comment]
@MatthewCroughan no no, there was an issue but I forced pushed a fix. Aligning the image to the centre (instead of to the left) seemed to fix it.

**Comment by MatthewCroughan** [comment]
Ah! The force pushing was completely silent, GitHub doesn't seem to show it here. Good to know I'm not going insane. @ldts

**Comment by MatthewCroughan** [comment]
Ah it shows it right underneath your initial commit. Missed it. My bad :)

**Pull request merged**
