### PR TITLE
rm: security: add UEFI provisioning 

### PR DESCRIPTION
**Pull request by ldts**
# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 7ebb85c48098c58c955c07720b92e6b75aa00065 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2744/docs/artifacts/html/index.html

**Comment by ldts** [comment]
@kprosise I believe the github errors do not apply

**Comment by doanac** [comment]
Docs for 9298a868235ab0803493284e7337a8f35dbef7ae are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2745/docs/artifacts/html/index.html

**Review by kprosise — APPROVED** [review]
LGTM

**Comment by ldts** [comment]
@kprosise can I merge or someone else needs to approve?
going to follow up with some qemu instructions

**Comment by ldts** [comment]
@caiotpereira ok?

**Comment by doanac** [comment]
Docs for 0e7bd897dd4e2077f4a56159071f5b6c12aca028 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2746/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 080563c4b6aca3f56b040d6c606dca2f1826f90d are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2748/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for b247e7e140242941b2d453eeb3faebd821134550 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2749/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
@ldts Squash the commits and I will go ahead and merge.

**Comment by doanac** [comment]
Docs for d83ea73065d8979f80eaf59b498b02bdade267ac are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2750/docs/artifacts/html/index.html

**Pull request merged**
