### PR TITLE
Cleanup first target tutorial

### PR DESCRIPTION
**Pull request by kprosise**
Applied style guidelines and language fixes.
New, updated screenshots added as webp format.
Removed master/devel and replaced with main.

QA Steps: Checked rendered output in html, and ran linter. Walked through steps where possible.

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

Biggest changes are new screenshots and changes to reflect the Fast First Target, namely the removal of master/dev branch, and replacing it with main. 

## Checklist

* [x] Run spelling and grammar check, preferably with linter.
* [x] Avoid changing any header associated with a link/reference.
* [x] Step through instructions (or ask someone to do so).
* [x] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [x] Match tone and style of page/section.
* [x] Run `make linkcheck`.
* [x] View HTML in a browser to check rendering.
* [x] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [x] follow best practices for commits.
  * [x] Descriptive title written in the imperative.
  * [x] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [x] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [x] Squash commits if needed.
* [x] Request PR review by a technical writer and at least one peer.

## Comments

We can add screenshots in other file formats if need be. There may be further info that needs to be updated/corrected which I missed. The main focus should be on getting this out for v91.

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 2e332af304163cb53a5665867eedb7a7d446a370 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2246/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for f8c75f3869d46b1648618973ab425842d430ddfc are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2247/docs/artifacts/html/index.html

**Review by angolini — COMMENTED** [review]
It seems to have some lines that are too long. Which is the rule we've been using for the line length? 
Some images still have master/devel, is the goal of this PR to replace that?
There is one merge commit that I think can be avoided.

**Comment by kprosise** [comment]
@angolini the guideline is semantic newlines with sentences \< 25 words, or column 100 if not using semantic newlines.

The language was changed, however obtaining screenshots is difficult with the new changes not being rolled out yet. I could go about it by creating new branches and tags for my Factory I suppose...

**Comment by angolini** [comment]
> @angolini the guideline is semantic newlines with sentences < 25 words, or column 100 if not using semantic newlines.

@kprosise I think that's the reason github softwrap the line (100 columns)
Thanks for the explanation

**Comment by doanac** [comment]
I can't comment on images, but here's what I'm seeing:
* `source/_static/tutorials/creating-first-target/tutorial-tag.png` - has "devel" in it.
* `source/_static/tutorials/creating-first-target/tutorial-containers.png` - has "devel" in it
* `source/_static/tutorials/creating-first-target/tutorial-find-build.png` - this is not what a new factory looks like. We don't do a "setup-creds" run or the other devel/master builds.

**Comment by kprosise** [comment]
@doanac would you be able to get me updated screenshots?

**Comment by kprosise** [comment]
Awesome possum!

**Comment by doanac** [comment]
Docs for b3d1ac1b2d96964d1622123caa0b99689d332b95 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2266/docs/artifacts/html/index.html

**Pull request merged**
