### PR TITLE
Go west

### PR DESCRIPTION
**Pull request by mbolivar**

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 8780dcc869834fb0c94c87cf353e27471eb28c8b are browesable at: https://ci.foundries.io/projects/fio-docs/builds/281/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 75d1199d9842fb003e967fc601a467b3fd250cb4 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/282/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 7b934306494d90e47861687ff48c517a05a7169b are browesable at: https://ci.foundries.io/projects/fio-docs/builds/283/docs/artifacts/html/index.html

**Comment by mike-scott** [comment]
Doc failure is odd.  I checked https://mgmt.foundries.io/leshan/#/security and it works fine.

**Comment by doanac** [comment]
I've used the docs to figure out how to get CI working, so +1 from me.

**Pull request merged**
