### PR TITLE
rpi3: replace img.gz with wic.gz

### PR DESCRIPTION
**Pull request by ldts**

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 543604893cc76c5c9e8e176e3116cee2305baa1c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/381/docs/artifacts/html/index.html

**Comment by ricardosalveti** [comment]
So, by default our CI will generate a img.gz file which is identical to wic.gz (which gets generated by default by the OE build system). IIRC we had that link as the traditional flashing tools were not able to identify wic.gz images, but they worked fine if renamed to img.gz. Can you give it a try if latest etcher (the one we recommend in the docs) is able to flash images ending with wic.gz?

If it works fine then we can simply just remove img.gz entirely, as that will make our docs easier to manage.

**Comment by ldts** [comment]
yes, etcher it is fine with wic images.

**Comment by doanac** [comment]
Docs for b6d3ea1838c3aa5bde3463b7f1a83e9f2a9c9966 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/383/docs/artifacts/html/index.html

**Pull request merged**
