### PR TITLE
README.md: add steps for building docs

### PR DESCRIPTION
**Pull request by igoropaniuk**
Add steps needed for building documentation locally.

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>

### CODE REVIEW

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Comment by doanac** [comment]
Ignore the CI failure.

@MatthewCroughan - interesting break caused by a new fioctl command: https://ci.foundries.io/projects/fio-docs/builds/747/docs/artifacts/console.log
~~~
/repo/source/reference-manual/factory/fioctl/fioctl_keys_ca_create.rst:20:Unexpected indentation.
~~~
I'll take a look right now

**Comment by doanac** [comment]
ci-retest  - fioctl has been updated to fix this https://github.com/foundriesio/fioctl/releases/tag/v0.14.1

**Comment by doanac** [comment]
Docs for 2e3a4e89ce8202e6d1bac2166a08bdf2113ec00b are browesable at: https://ci.foundries.io/projects/fio-docs/builds/748/docs/artifacts/html/index.html

**Pull request merged**
