### PR TITLE
Add technical details of api tokens

### PR DESCRIPTION
**Pull request by doanac**
Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 9577241716bf92ce3ce2473705396ff734a4eca7 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/531/docs/artifacts/html/index.html

**Comment by doanac** [comment]
@MiloCasagrande @mike-sul @MatthewCroughan  - this is an early WIP, but I'm trying to start writing down the details. There's a big piece missing for fioctl's use of oauth2 that's yet to be sorted out. This lays the ground work and a place we can track things.

**Comment by mike-sul** [comment]
@LGTM, of course `fioctl's use of oauth2` should be documented too.

**Comment by doanac** [comment]
Docs for 89a108b8906594e36ca9061ad96312725084edcc are browesable at: https://ci.foundries.io/projects/fio-docs/builds/546/docs/artifacts/html/index.html

**Comment by doanac** [comment]
@MatthewCroughan - i think this is starting to reflect reality. shouldn't be too long till this is ready.

**Comment by doanac** [comment]
Docs for 8bc03766b9d8edbefd1ee600c01532647d7ff7a1 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/548/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for d361d18efa48d5d01c8c5d783fe2e400e5a433f1 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/675/docs/artifacts/html/index.html

**Comment by doanac** [comment]
@MatthewCroughan - this is ready now that the new site is up

**Review by MatthewCroughan — COMMENTED** [review]
Should we even bother using inserting the `<factory>` placeholder? Since the user has no control over this, and will never have to replace or write this text in a terminal or file, it may be a bit confusing on first read. What do you think?

**Comment by doanac** [comment]
I just found it confusing without the place holder. eg - there is no `ci:read` scope. I did wonder myself though.

**Review by MatthewCroughan — APPROVED** [review]
> I just found it confusing without the place holder. eg - there is no `ci:read` scope. I did wonder myself though.

I would say that a `<factory>` in this context is a constant and not a variable, so should not be included. But maybe this is more of a general change that we should approach in the future by removing the factory name from visibility in places where they're not a variable that the user can change, such as this.

**Comment by doanac** [comment]
@MatthewCroughan - just force pushed a change with `<factory>:` removed.

**Comment by doanac** [comment]
Docs for 9979b00c11d6edda2183ad94a460691464f421c8 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/679/docs/artifacts/html/index.html

**Comment by MatthewCroughan** [comment]
I think that reads a lot better since it is generic. I think people will understand when reading in the new ui that this is preprended to help them understand what factory this token applies to. Would only be an issue if a user was trying to manage multiple factories, which is quite rare already.

**Pull request merged**
