### PR TITLE
aktualizr block diagram

### PR DESCRIPTION
**Pull request by ldts**
Improve documentation by adding a block diagram as well as explicitly declaring aktualizr responsibilities,

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 5f5cccaf8bf080b2e603930cb739f00ff69841c1 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/528/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Looks pretty good. Just some small nits on the diagram since we are publishing it:

 * the package manager code no longer lives in libktualizr. Its a "plugin" we own in our aktualizr-lite tree.
 * the package manager talks to OSTREE and docker-compose
 * Step 7 should just be "generates installation reports". It does not receive them.

I'm not sure how to convey OPTEE. That's one thing p11 can talk to, but we aren't specifically tied to that (eg - I use softshm)

**Comment by ldts** [comment]
@doanac thanks Andy. Let me know if this looks a bit more accurate

**Comment by doanac** [comment]
Docs for 5e491aab0f60c38512d543e98c630df55cefcb8d are browesable at: https://ci.foundries.io/projects/fio-docs/builds/529/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 923ff0f6a6f7b0cf124f45b746f729d5b035c463 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/530/docs/artifacts/html/index.html

**Comment by ldts** [comment]
@doanac ok so done with this?

**Comment by doanac** [comment]
yep. +1

**Pull request merged**
