### PR TITLE
Fix broken link to ti documentation

### PR DESCRIPTION
**Pull request by kprosise**
Removed link which was resulting in a 404. No suitable alternative found, and does not seem necessary.

QA Steps: Read page to make sure link could be removed without major loss of information. Ran Linkcheck and built documentation. No issues spotted.

No issues to link, minor fix.

# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

* [ ] Run spelling and grammar check, preferably with linter.
* [x] Avoid changing any header associated with a link/reference.
* [x] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [x] Run `make linkcheck`.
* [x] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [x] follow best practices for commits.
  * [x] Descriptive title written in the imperative.
  * [x] Include brief overview of QA steps taken.
  * [x] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [x] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [x] Squash commits if needed.
* [x] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for db27378c8b9328f935dff5c3680415bdd1fc1108 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2630/docs/artifacts/html/index.html

**Review by vanmaegima — COMMENTED** [review]
I can't comment on this change, maybe we should drop ``gp`` entirely?
I'm okay with whatever @quaresmajose says it's supported on LmP.

**Review by MrCry0 — COMMENTED** [review]
I'd drop the gp entirely.

**Comment by quaresmajose** [comment]
> I can't comment on this change, maybe we should drop `gp` entirely? I'm okay with whatever @quaresmajose says it's supported on LmP.

I don't about the am64 board because I do not have any but for am62 the variant I have is the `gp`.
In LmP we support what is supported upstream https://git.yoctoproject.org/meta-ti/tree/meta-ti-bsp/conf/machine/am64xx-evm-k3r5.conf?h=kirkstone that default for the `hs-fs`.
I don't know if `gp` versions are still sold but I believe so.

**Review by quaresmajose — APPROVED** [review]

**Comment by kprosise** [comment]
I will keep `gp` in there for the time being then.

**Pull request merged**
