### PR TITLE
extensions/rpi3: use mp version for github artifacts

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**
Use the microPlatform version for github artifacts urls.

Signed-off-by: Tyler Baker <tyler@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 9ec932320b003b9902e871e9422853e0700658b2 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/278/docs/artifacts/html/index.html

**Comment by doanac** [comment]
oops. good catch

**Comment by doanac** [comment]
Docs for dc7144a1edcbeb3d73e4f8ca8f23740ace141f72 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/279/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 7b5823e23e79437bf2a415ebf4c9c479268aa4c5 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/280/docs/artifacts/html/index.html

**Comment by EmbeddedAndroid** [comment]
Will this need to be cherry-picked onto the mp-38 tag?

**Comment by doanac** [comment]
no. I think i just need to regenerate the docs once this has been merged. Then going forward it will "just work"

**Comment by doanac** [comment]
Docs for f841789e31dcd6c32040fa1fb844b1548820675b are browesable at: https://ci.foundries.io/projects/development/website/builds/3/unit-test/artifacts/html/index.html

**Pull request merged**
