### PR TITLE
rm: CI LUKS encryption

### PR DESCRIPTION
**Pull request by ldts**
Document the variables that control CI disk encryption.

# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 0dfa7a362818165fe158f0b26feffb6e0187643b are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2754/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for c99f43ce967630afc871535e7ac55f3ec9ecb487 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2755/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 8f93315b9433cd968c343ac04eb4c70fffcf8140 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2756/docs/artifacts/html/index.html

**Comment by ldts** [comment]
@kprosise can we merge?

**Comment by kprosise** [comment]
> @kprosise can we merge?

We should follow the process—which I've admittedly been a bit lax about lately for small changes—for the doc PRs. So along with my review, we need (1) a peer…whoever else best understands the technical content/subject, and (2) Customer Success, such as @vanmaegima or @caiotpereira

**Review by vanmaegima — APPROVED** [review]
LGTM

**Review by kprosise — APPROVED** [review]
LGTM

**Comment by ldts** [comment]
@quaresmajose can you check/approve this change please? I have ignored documenting the actual passphrase configuration at this point since it requires a fix in initramfs and that needs to be planned.

**Review by quaresmajose — APPROVED** [review]
LGTM

**Pull request merged**
