### PR TITLE
gs: review chapter

### PR DESCRIPTION
**Pull request by vanmaegima**
This review focused on reordering information, dropping unsupported and irrelevant information, making steps platform agnostic, all targetting clarity and better understanding for a new user.

Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for f6ed85e6082ce188305a5f867486ba13296321a4 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1957/docs/artifacts/html/index.html

**Review by kprosise — APPROVED** [review]
LGTM. Thank you so much for this!

**Comment by kprosise** [comment]
You have my okay to go ahead and merge this commit whenever you are ready.

**Review by angolini — APPROVED** [review]

**Comment by doanac** [comment]
Docs for 15c7086c05bc0e97b8117298db156a3d250ce60b are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1962/docs/artifacts/html/index.html

**Comment by dagriego** [comment]
This is now in main

**Pull request closed without merging**
