### PR TITLE
boards: removing iMX8Q traces from iMX8MM page

### PR DESCRIPTION
**Pull request by munoz0raul**

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 9a3286d949ef2386cddd209f8c580b4e2e8fcf71 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1141/docs/artifacts/html/index.html

**Review by vanmaegima — APPROVED** [review]

**Comment by MrCry0** [comment]
@munoz0raul IMHO this commit is more about adding the "iMX8MQ prepare" page.
Wouldn't it be more clear if reflect this in the commit message?

**Comment by doanac** [comment]
Docs for 7c41fa6a0176e255ec1fa8c8be66aa6b1a18d671 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1142/docs/artifacts/html/index.html

**Comment by munoz0raul** [comment]
@MrCry0 I just updated the commit message. Hope it clarifies why I changed it.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Pull request merged**
