### PR TITLE
Update for fast first target master to main

### PR DESCRIPTION
**Pull request by kprosise**
Instances where master branch should be changed to main were implemented. Not all were directly related to the Fast First Target/customer repos; links and references to meta-lmp were also updated to main.

QA steps: built html and linkcheck. As the focus was on keeping things atomic, linter warnings were ignored, as difficult as it was.

This commit addresses FFTK-2430  
This commit addresses FFTK-860

## Readiness

*   [x] Merge (pending reviews)
*   [ ] Merge after _date or event_
*   [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._  
_You can fill this out after opening the PR. "Did I..."_

*   [ ] Run spelling and grammar check, preferably with linter.
*   [x] Avoid changing any header associated with a link/reference.
*   [ ] Step through instructions (or ask someone to do so).
*   [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
*   [x] Match tone and style of page/section.
*   [x] Run `make linkcheck`.
*   [ ] View HTML in a browser to check rendering.
*   [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
*   [x] follow best practices for commits.
    *   [x] Descriptive title written in the imperative.
    *   [x] Include brief overview of QA steps taken.
    *   [x] Mention any related issues numbers.
    *   [x] End message with sign off/DCO line (`-s, --signoff`).
    *   [x] Sign commit with your gpg key (`-S, --gpg-sign`).
    *   [x] Squash commits if needed.
*   [x] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._  
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for cf06c30fac5a3c15b6c89501660a6282953efa94 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2256/docs/artifacts/html/index.html

**Review by angolini — APPROVED** [review]
This kind of PR is hard to review. I tested the links and looked if there were any weird changes. For me, it looks good!

**Comment by kprosise** [comment]
I want to make sure I did not change any links which should not have been changed regarding master -> main in our repos

**Review by doanac — APPROVED** [review]
wow. thanks.

**Pull request merged**
