### PR TITLE
doc: updates for nRF52840-DK and OpenThread

### PR DESCRIPTION
**Pull request by mike-scott**
- Mainly this series is for adding nRF52840-DK / OpenThread instructions.
- Also includes some rewording for some LmP pages

### CODE REVIEW

**Comment by mike-scott** [comment]
@gcgrey I re-arranged and squashed the patches as needed and addressed the majority of my comments from the other PR.

Please review as you have time.

**Comment by doanac** [comment]
Docs for bab8cb66ca06e6b4c96760fff648438534c3fc25 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/295/docs/artifacts/html/index.html

**Comment by mike-scott** [comment]
Reset the patch dates to fix review order

**Comment by doanac** [comment]
Docs for 86fe621c76365270b2d532229f676fe3886ef015 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/296/docs/artifacts/html/index.html

**Comment by mike-scott** [comment]
Missed 1 area in installation-zephyr where I had nRF52-DK and nRF52840-DK reversed still.

**Comment by doanac** [comment]
Docs for aca0f11bf23cdcde2fed49c0d909f4ffb3f1647b are browesable at: https://ci.foundries.io/projects/fio-docs/builds/297/docs/artifacts/html/index.html

**Comment by mike-scott** [comment]
Missed a reference to CONFIG_NET_APP_ setting in the K64F network include file.

**Comment by doanac** [comment]
Docs for f822aa9dd9489002bea80d4ecce28208504861a9 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/298/docs/artifacts/html/index.html

**Comment by mike-scott** [comment]
Going to merge this now and we can do another PR to fix anything missed.

**Pull request merged**
