### PR TITLE
(readme): small fix and add notes to help out new users

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

- Correct the command for executing the requirements.
- Include two notes to guide new users and prevent potential issues.

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [x] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 18992cf20af20fd3ea62faeb6e771015f3e03fa6 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2347/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 50479fe3a63cab1ffff4881b31d974995db4b7e1 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2348/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for b6e5145f713d5ac15dd8929b5afec3a97a31a697 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2349/docs/artifacts/html/index.html

**Review by angolini — APPROVED** [review]
I would avoid using icons. But I will @kprosise decide about that. Other than that LGTM.

**Review by kprosise — APPROVED** [review]
LGTM! Thank you for this!

**Pull request merged**
