### PR TITLE
Apply new RTD theme options

### PR DESCRIPTION
**Pull request by kprosise**
Applied theme changes that are configurable without modifying CSS or HTML. Deeper changes to the theme can always be investigated later.

Changes of note:

* "+" symbol in sidebar next to sections which can be expanded to show subsections. We may wish to investigate changing the color to increase visibility, if this is an option we want to add to the docs.

* Background color of sidebar updated to match website

* External links are styled, so as to indicate such.

QA steps: viewed rendered html in browser, ran linkcheck.

No associated issue, minor changes to test out.

# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

* [ ] Run spelling and grammar check, preferably with linter.
* [x] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [x] Run `make linkcheck`.
* [x] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [x] follow best practices for commits.
  * [x] Descriptive title written in the imperative.
  * [x] Include brief overview of QA steps taken.
  * [x] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [x] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [x] Squash commits if needed.
* [x] Request PR review by a technical writer and at least one peer.

## Comments

This is just to test out some theme options, to see if we wish to adopt any of them.

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 81bce4dca51adc708845f44e3d24ac0a6f540ac2 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2729/docs/artifacts/html/index.html

**Comment by vanmaegima** [comment]
Looking good. I like the `+` addition.

**Review by MrCry0 — APPROVED** [review]

**Comment by kprosise** [comment]
I changed the background color for the ToC sidebar, which makes the "+" a bit more visible.

**Comment by doanac** [comment]
Docs for 238994d1ccbecb1fddcd5602d61b52c98f890c9a are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2730/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
Linkcheck error can be ignored.

**Pull request merged**
