### PR TITLE
Branding for Foundries and Yocto Project

### PR DESCRIPTION
**Pull request by angolini**

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 9ef24159be047faf7de12c379e9483afe5e7464c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/774/docs/artifacts/html/index.html

**Review by MatthewCroughan — APPROVED** [review]
It may be possible to add these kinds of checks into the CI. Can you think of a way to do it without false positives via `grep`? Great work :)

**Review by vanmaegima — APPROVED** [review]

**Comment by angolini** [comment]
Maybe for the "Yocto Project", the problem here is that "Yocto Project" not always is a perfect match for "yocto" people use to say. I mean, people are used to describe all and everything from the yocto project using "yocto", but sometimes they mean _the Yocto Project's tools_, or _the Yocto Project's build system_

For the LmP, I let behind all the references for meta-LMP, one occurrence inside an included patch. I might get back to it and change them as well.

What do you think?

**Comment by MatthewCroughan** [comment]
> Maybe for the "Yocto Project", the problem here is that "Yocto Project" not always is a perfect match for "yocto" people use to say. I mean, people are used to describe all and everything from the yocto project using "yocto", but sometimes they mean _the Yocto Project's tools_, or _the Yocto Project's build system_
> 
> For the LmP, I let behind all the references for meta-LMP, one occurrence inside an included patch. I might get back to it and change them as well.
> 
> What do you think?

I think using *Yocto* to refer to everything is colloquially accepted. As far as I'm aware, Yocto is nothing more than a reference distribution created with BitBake/OpenEmbedded. So it's the OpenEmbedded build system, which is implemented via BitBake. Yocto then maintain *Poky*, a reference distribution for people to fork from.

Yocto ensures a healthy community, they maintain certain OE layers. But Yocto itself is not the build system, that would be OpenEmbedded + BitBake.

**Comment by angolini** [comment]
The brand guideline from Yocto Project states that "yocto" a should never be used alone, in a document.

And yes, people has been using yocto colloquially and it's getting more and more common nowadays.

**Comment by ricardosalveti** [comment]
> Maybe for the "Yocto Project", the problem here is that "Yocto Project" not always is a perfect match for "yocto" people use to say. I mean, people are used to describe all and everything from the yocto project using "yocto", but sometimes they mean _the Yocto Project's tools_, or _the Yocto Project's build system_
> 
> For the LmP, I let behind all the references for meta-LMP, one occurrence inside an included patch. I might get back to it and change them as well.
> 
> What do you think?

Sounds good, wonder if we should call the layer meta-LmP or just meta-lmp. Guess meta-lmp is part of the Linux microPlatform project? Because lmp itself is just a layer, for the full LMP we need the yocto/oe-core stuff :-)

**Review by ricardosalveti — APPROVED** [review]
Great stuff, thanks for cleaning this up.

**Pull request merged**
