### PR TITLE
ug: include personas

### PR DESCRIPTION
**Pull request by vanmaegima**
# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

This includes a doc view based on personas for easier customer interaction.

## Checklist

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by vanmaegima** [comment]
@angolini I've tried to address your comments from the first PR.

**Review by kprosise — APPROVED** [review]
LGTM.

**Comment by kprosise** [comment]
Note regarding build failure: Issue have been fixed (and was unrelated to the PR).

**Review by angolini — APPROVED** [review]
Some concepts are still not clear to me, but I don't have anything against this doc so let's LGTM

**Comment by kprosise** [comment]
@vanmaegima It is fine by me to go ahead and merge this as soon as you are ready.

**Comment by vanmaegima** [comment]
@kprosise we're holding on this one a bit more to get more internal inputs.

**Review by MrCry0 — APPROVED** [review]

**Comment by kprosise** [comment]
@vanmaegima did we want to keep this open, or should we close it? I am fine either way.

**Pull request closed without merging**
