### PR TITLE
ug: dg: Move PKI setting details from rf to ug

### PR DESCRIPTION
**Pull request by mike-sul**
Signed-off-by: Mike <mike.sul@foundries.io>

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [x] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [x] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [x] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 9302b186daa3a3cdf9f5c58111cc6f20d9cc976a are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1543/docs/artifacts/html/index.html

**Comment by mike-sul** [comment]
This is just movement of `Under the hood` section from `reference-manual/security/device-gateway.rst` to `user-guide/device-gateway-pki/device-gateway-pki.rst`.
Also, some lint errors are fixed.

**Review by kprosise — APPROVED** [review]
LGTM

**Comment by doanac** [comment]
Docs for aaa91f60bbfd8683dc99b9041018b99d5f38e7f2 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1544/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
@mike-sul you can go ahead and merge this whenever you are ready.

**Comment by doanac** [comment]
@kprosise - one thing we also need to do related to this is the title of that page `Managing Your Device Gateway`. We've gotten feedback that people think it means they'll have to run their own device gateway which isn't what we were trying to say.

**Comment by mike-sul** [comment]
> one thing we also need to do related to this is the title of that page Managing Your Device Gateway.

@doanac Would you like me change it in this PR?
It could be `Managing Device Gateway PKI` or `Managing Factory PKI`...

**Comment by doanac** [comment]
i don't mind changing the title here. I'm not sure what that title should be, but it's as good a time as any.

**Review by doanac — APPROVED** [review]
nice. thanks

**Pull request merged**
