### PR TITLE
secure-boot: add block diagram

### PR DESCRIPTION
**Pull request by ldts**
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for cd095d89e40d5b7b61975906cffff97cdff4a69e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/414/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for ce27c329dea1445d16aeaea7ef6729565b730ba3 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/415/docs/artifacts/html/index.html

**Comment by ricardosalveti** [comment]
Minor thing, LMP should be "Linux microPlatform".

Also RPMB gets used via U-Boot and Linux, but not sure if there is an easy way to show that here.

But looking great, thanks for putting this together.

**Comment by ldts** [comment]
yeah I wasnt sure if doing the loop via uboot/linux for rpmb would obscure things ...I'll try

**Comment by doanac** [comment]
Docs for c64531a065559d6d4824bdb43b14901994437359 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/417/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 296d640d8600e39fec70d7f447cf7f699876bfc7 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/418/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 1bbfb32f677e6ad28ae6af10b3d85afdf1e242f4 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/419/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for d8fdd38f40555ed2366aefcdfa7607164a1d4847 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/420/docs/artifacts/html/index.html

**Pull request merged**
