### PR TITLE
rm: Add device factory reset

### PR DESCRIPTION
**Pull request by mwasilew**
Describe how to revert any device changes to bring it back to 'fresh manufacturing' state.

Signed-off-by: Milosz Wasilewski <milosz.wasilewski@foundries.io>

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

Describe feature already present in LmP but not yet documented.

## Checklist

* [x] Run spelling and grammar check, preferably with linter.
* [x] Avoid changing any header associated with a link/reference.
* [x] Step through instructions (or ask someone to do so).
* [x] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [x] Match tone and style of page/section.
* [x] Run `make linkcheck`.
* [x] View HTML in a browser to check rendering.
* [x] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [x] follow best practices for commits.
  * [x] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [x] Request PR review by a technical writer and at least one peer.

### CODE REVIEW

**Comment by doanac** [comment]
Docs for dd959fbc9a9e7196210df327faeb2ab486cff0b4 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1800/docs/artifacts/html/index.html

**Review by angolini — APPROVED** [review]
This doc page is beautiful!

I miss two points, but I think they are optional in fact. 

Is a `fioclt` command needed to create the `.factory_reset*` files from the host?
is a cross-reference needed to define what "from ostree" is? Maybe point to https://docs.foundries.io/latest/reference-manual/ota/static-deltas.html?

Anyway, I'm just saying, if you don't think it's needed you can ignore my comment.

**Comment by mwasilew** [comment]
I don't think we have a mechanism to create the files (@rsalveti ?). In other words, we have means to reset the device, but no way to trigger the reset remotely. At least I'm not aware of such possibility.

**Comment by ricardosalveti** [comment]
We don't have yet a mechanism for doing that via fioctl/fioconfig, but it might indeed be useful to have later on.

**Review by ricardosalveti — APPROVED** [review]
LGTM, thanks a lot for doing this @mwasilew !

**Comment by doanac** [comment]
Docs for 274f137543dbb938be549c450be52663d41d43fb are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1801/docs/artifacts/html/index.html

**Review by kprosise — APPROVED** [review]
L G T M!

**Pull request merged**
