### PR TITLE
ug: Minor fixes in aklite CLI documentation

### PR DESCRIPTION
**Pull request by detsch**
A few fixes that I've missed from PR #734.

---
# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by detsch** [comment]
@kprosise , just noticed the adjustments for some of your suggestions were missing in PR #734. File was not saved to the last state when I've executed the commit amend command 🤦. Sorry about that.  Please merge this PR as well to fix it.

**Comment by doanac** [comment]
Docs for 9baa24cb9948166d35e9d6b9facb741e1a9bef94 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2768/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
> @kprosise , I've just noticed the adjustments for some of your suggestions were missing in PR #734. File was not saved to the last state when I've executed the commit amend command 🤦. Sorry about that. Please merge this PR as well to fix it.

No worries, I should have caught that myself!

**Review by kprosise — APPROVED** [review]
Thanks! Will go ahead and merge now

**Pull request merged**
