### PR TITLE
Include a vale run in CI

### PR DESCRIPTION
**Pull request by doanac**
This should help making the number issues more obvious to everyone.

Signed-off-by: Andy Doan <andy@foundries.io>

## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [x] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 4fc9243d4f04067bd71ca0e3f1bbac0d1839cf59 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1567/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 547a589674c3c493cfac4bf4509ddb799775c74b are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1568/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 001d23bdfa8affdb8b25f0cd51f40134562188df are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1569/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 832bde7053d373ca57f3e9bc8776a159908f0cd6 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1570/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
I need to make some additional changes to fio-style. There's additional suggestions which I will provide soon.

**Comment by doanac** [comment]
yep. this is sort of garbage, cause i dont know what I'm doing. i will try and get back to looking at it soon though.

**Comment by kprosise** [comment]
> yep. this is sort of garbage, cause i dont know what I'm doing. i will try and get back to looking at it soon though.

One thing to note is that `fio-style` should not be cloned.  After vale is installed,  running `vale sync` will pull in the fio-style release package, as well as any additional styles that fio-style uses, and set up the folders and all. The packages vale will get are already defined in  `docs/.vale.ini`

**Comment by doanac** [comment]
Docs for f2215e598db8a76f1adb15b0ee357183b177f2a0 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1571/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for ef53ab8e7dfff900c71a02e0e6b83719c7899c7e are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1572/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
@doanac it worked I see! If you look in the Makefile, I try to have it check only the file(s) with change. Also a lot of the errors Vale reports I need to change to Warnings.

**Comment by kprosise** [comment]
Also, here's the official [Vale GitHub action](https://github.com/errata-ai/vale-action).

**Comment by doanac** [comment]
Docs for 931e875b1bf7fdf0390a9063df3b77e413875c2d are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1573/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
hi @doanac, I'll be returning to this soon, with the goal of having all the linter stuff (integration, rules, workflow, internal documentation on how to use) done by end of the year.

**Pull request closed without merging**
