### PR TITLE
sphinx: add requirements.txt to keep track of dependencies

### PR DESCRIPTION
**Pull request by MatthewCroughan**
Most sphinx projects have a requirements.txt at the root of their doctree to list sphinx extensions and their versions, currently that's just hidden in the form of a pip install command in jobserv that is pasted twice and doesn't have versions for the packages.

Jobserv will now run `pip install -r ./requirements.txt` and if we need to add extensions they'll be added to `requirements.txt` instead of updating the `jobserv.yml`

I've based the versions in requirements.txt on the latest, since that's what I have been using on my machine and seemingly has no regressions in the html output from what I see hosted online now. However, the actual versions that are being used by jobserv are not listed anywhere. 

```
sphinx-rtd-theme==0.5.0
sphinx==3.1.2
sphinxcontrib-contentui==0.2.5
```

### CODE REVIEW

**Comment by EmbeddedAndroid** [comment]
From jobserv:

`ERROR: Invalid requirement: './requirements.txt'
Hint: It looks like a path. It does exist.The argument you provided (./requirements.txt) appears to be a requirements file. If that is the case, use the '-r' flag to install the packages specified within it.`

**Comment by MatthewCroughan** [comment]
I have no idea how I missed that lol. Are force pushes okay?

**Comment by doanac** [comment]
Docs for b00a1481c3dfb5b78dede19b0cf836f3563f0851 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/483/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for b6a320b3ca68c5aa8fb855cbff2fd9101d221ccc are browesable at: https://ci.foundries.io/projects/fio-docs/builds/484/docs/artifacts/html/index.html

**Comment by MatthewCroughan** [comment]
Additionally I'm adding `sphinx-tabs` so that we can add cases for various things like shown in this gif.

tabs

**Pull request merged**
