### PR TITLE
rm: troubleshooting: minor fixes

### PR DESCRIPTION
**Pull request by vanmaegima**
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 29677515ef01823c7044b1ec4125b2399d834438 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1396/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
(Link-check failure due to an external site linked to being down for a moment, can be ignored)

**Review by kprosise — APPROVED** [review]
LGTM!

**Comment by doanac** [comment]
Docs for c9e6b930d44b8106bf2b7ef0a1f37476037a3668 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1397/docs/artifacts/html/index.html

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]
LGTM

**Pull request merged**
