### PR TITLE
Change usage for device tags

### PR DESCRIPTION
**Pull request by doanac**
The backend for sometime has only allowed devices to subscribe to a
single tag. This updates our docs to use the new fioctl --tag option so
that we start saying this in the singular form.

Additionally - the "--tags" option was removed from the tutorials as its
not required.

Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
@MatthewCroughan - not sure if i did the asciicinema stuff right. They don't render locally.

**Comment by doanac** [comment]
@munoz0raul - take a look at the tutorial changes and make sure this makes sense to you.

**Comment by doanac** [comment]
Docs for 96c03da69c85afe78bc7547826b6df029da86f66 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/951/docs/artifacts/html/index.html

**Comment by munoz0raul** [comment]
@doanac , the tutorial, working with tags is not public yet.

As far as I understood, this tutorial will be affected and the example in the documentation below will not work anymore:

https://ci.foundries.io/projects/fio-docs/builds/939/docs/artifacts/html/tutorials/working-with-tags/following-specific-tag.html#following-an-specific-tag

`fioctl targets tag --by-version -T devel,tutorial 10 -f <factory>`

**Comment by doanac** [comment]
It will still work because I've kept a hidden option for tags to keep backward compatibility. However, we should update that to use the improved wording.

**Pull request merged**
