### PR TITLE
Correcting photo subtitles

### PR DESCRIPTION
**Pull request by munoz0raul**
I just noticed now that all photos in the AWS Tutorial are with the same subtitles.

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 3fcc7b82726adba13ef8c44d4f4c36e48dbd6617 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/448/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for ea4817b1b5c3935d4936f8133ec4744b5ffb5321 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/449/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 877f8be8188a8d90dfac296a3c3dc81466e38912 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/450/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for e7ef3be76b8cd083961d9e542b8be9e2a1856bc2 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/452/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 7dc55c57a214b110b179160174a0d9d0db6345c5 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/453/docs/artifacts/html/index.html

**Comment by EmbeddedAndroid** [comment]
LGTM, can you rebase this on master?

**Comment by doanac** [comment]
Docs for 74c9cb2a6ecdec1ee7b54d11ed752cb0eebb5652 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/489/docs/artifacts/html/index.html

**Pull request merged**
