### PR TITLE
Add reference for device gateway PKI

### PR DESCRIPTION
**Pull request by doanac**
Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Hey guys, I'm not real happy with this, but its a really difficult topic for me to articulate clearly. `fioctl keys ca` and `fioctl keys ca create --help` both provide a lot of context.

@MatthewCroughan - I think ricardo will have to first help with the technical writing, and then we can get you involved on polishing this.

**Comment by doanac** [comment]
Docs for 5d022a129d9a3d29424d50e4aa71d453f1729df3 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/737/docs/artifacts/html/index.html

**Review by ricardosalveti — APPROVED** [review]
I think this is a good start, but later we should probably extend a bit by saying why owning the gateway PKI is important, and things to be aware of.

This is a complex topic, so maybe we should later have a few links for stuff people need to be familiar with before trying it out :-)

**Review by MatthewCroughan — APPROVED** [review]
Whatever inadequacies you think are present are not important, I understood this and I think it can be improved upon iteratively. LGTM.

**Pull request merged**
