### PR TITLE
Minor fixes for the lmp installer qemu instructions

### PR DESCRIPTION
**Pull request by ricardosalveti**
## Readiness

* [ ] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 23b0c480277e8549786b427f1c68665879557dc7 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1687/docs/artifacts/html/index.html

**Review by angolini — APPROVED** [review]

**Review by mike-scott — APPROVED** [review]
LGTM

**Review by kprosise — APPROVED** [review]
LGTM

**Comment by kprosise** [comment]
Changes look fine, and I can merge when ready. Please remember to fill out the PR Template for all doc PRs. (I may add an option for small changes where most of the checklist does not apply in the near future.) The readiness section is particularly helpful. Also all commits should be both signed and signed-off to avoid having the merge blocked and requiring bypassing branch protections.

**Pull request merged**
