### PR TITLE
authentication-xilinx: add instructions about registering the PUF

### PR DESCRIPTION
**Pull request by ricardosalveti**
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 54aa2d91697cf2960d1e641677063fcfd9039e8b are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1211/docs/artifacts/html/index.html

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by vanmaegima — APPROVED** [review]
LGTM

**Comment by kprosise** [comment]
No issues detected.

**Pull request merged**
