### PR TITLE
Add document about team based access

### PR DESCRIPTION
**Pull request by doanac**
Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for eca0fe930c790f900bd21564482d8dbfe8ce952e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/999/docs/artifacts/html/index.html

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]

**Comment by doanac** [comment]
rebased on master

**Comment by doanac** [comment]
Docs for c82839db30d909757c529a76e7efd3f8c9ed1ac7 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1017/docs/artifacts/html/index.html

**Pull request merged**
