### PR TITLE
Add offline documentation via pdf

### PR DESCRIPTION
**Pull request by kprosise**
Added basic configuration and support for generating PDF version of the documentation. This is done with simplepdf.

Also added to the jobserv.yml file for PR requests, which will need to be tested.

QA steps: built PDF and HTML. Checked that HTML would build with missing PDF. Checked that PDf download worked from both top index page and any other page. Checked that PDF links worked and output was readable. Note that simplepdf will report errors due to links in sidebar.These can be ignored.

This commit addresses task FFTK-1795
This commit applies to FFPK-93
This commit applies to FS-1826

# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [x] Draft

## Overview

PDF download in Footer

## Checklist

* [ ] Run spelling and grammar check, preferably with linter.
* [x] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [x] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [x] follow best practices for commits.
  * [x] Descriptive title written in the imperative.
  * [x] Include brief overview of QA steps taken.
  * [x] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [x] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [x] Squash commits if needed.
* [x] Request PR review by a technical writer and at least one peer.

## Comments

Will need to make sure that PR builds; there are a couple potential issues.
* May require libraries to be installed in order to build PDFs
* Increases build time of documentation substantially

### CODE REVIEW

**Comment by kprosise** [comment]
Looking into build failure now, and indeed, there were issues installing some of the new dependencies.

**Comment by doanac** [comment]
Docs for 3055c98504cba7dbd3cb16ead3dbf8b832eebab7 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2711/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for b672e771fa62b50d27dd5fd45572121d962727c8 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2712/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
Builds...and is available, however page numbering and links to pages from index are off

**Comment by doanac** [comment]
Docs for f44a7e0e1c0f54d552e68d0fca1aaa8734050add are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2716/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 09a7400b77c1405738f0bcafeded13191cf342fc are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2718/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
The note added to the main index mentions the HTML release as the ideal way to view the docs, and mentions the pdf link in the footer. PDF was not linked in the admonition on purpose; if a customer still wishes to download it they may, but a PDF will never be the optimized way of reading the docs.

**Review by angolini — APPROVED** [review]
I approve the PR as it is today! But I want to make some comments just in case.

* I like the home page with maxdepth=2 in the HTML
* Is there a reason why the pdf version is not available along with the HTML under the github release tab? If in the future, if we decide to also provide pdf in the release tab, the tip will be outdated. I would not mention "HTML version" in the tip, would say something as "offline version available" or something.
* for me, it looks like "Note that some elements in the PDF, such as board flashing sections, do not render correctly." is something to be added to the Release Notes. I don't think it hurts to keep this in the first page, however, I will never trust I will remember to remove it in case the pdf is fixed in the future.
* this whole "offline version" for the docs is something to go to the RN as well

**Comment by angolini** [comment]
oh! I just remember I don't know if next doc release will be decoupled from lmp release having a different RN

**Comment by doanac** [comment]
Docs for e64d238526e1c685e36e11de02c5ebdd8b845461 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2726/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 65b243ea431341ee0b2faecab7f338d850879e19 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2727/docs/artifacts/html/index.html

**Comment by kprosise** [comment]
GitHub guided merge conflict resolution via the web-editor didn't help much. It will be quicker and likely simpler to close this PR and open a new one, with some additional changes.

**Pull request closed without merging**
