### PR TITLE
Cleanup Git config page

### PR DESCRIPTION
**Pull request by kprosise**
Applied style guide rules, and shortened text in a number of areas.

Updated image to reflect redesigned Web-UI, and added an additional screenshot to show where the `+ credentials` button is on screen.

QA: Ran linkcheck, Vale, and examined rendered output.

No Jira issue to tag.

Signed-off-by: Katrina Prosise <katrina.prosise@foundries.io>

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

General cleanup.

## Checklist

* [x] Run spelling and grammar check, preferably with linter.
* [x] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [x] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [x] Match tone and style of page/section.
* [x] Run `make linkcheck`.
* [x] View HTML in a browser to check rendering.
* [x] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [x] follow best practices for commits.
  * [x] Descriptive title written in the imperative.
  * [x] Include brief overview of QA steps taken.
  * [x] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [x] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [x] Squash commits if needed.
* [x] Request PR review by a technical writer and at least one peer.

### CODE REVIEW

**Comment by doanac** [comment]
Docs for f2afbb291ece1e91932729357b8747ac2a9bd8ef are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1910/docs/artifacts/html/index.html

**Review by vanmaegima — APPROVED** [review]
LGTM

**Review by angolini — APPROVED** [review]

**Comment by doanac** [comment]
Docs for add1bce39f43c4a1211b3a3d08e296cc2f846b1e are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1911/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 1b456d7a8d4ed7e28fa34aaf2697d0c8a403e049 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1913/docs/artifacts/html/index.html

**Pull request merged**
