### PR TITLE
Add a go-to-production document

### PR DESCRIPTION
**Pull request by doanac**
Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
@mike-scott @ricardosalveti - I think there's more we can/should add here. I'm posting it in hopes we can collect more information and get this complete enough for now.

**Comment by doanac** [comment]
Docs for ff90ab5f419f97e64be3b6b94772f51ed354062d are browesable at: https://ci.foundries.io/projects/fio-docs/builds/844/docs/artifacts/html/index.html

**Comment by doanac** [comment]
@rsalveti @mike-scott - this thing is starting to bit rot. we may want to sit down next week and discuss

**Comment by ricardosalveti** [comment]
> @rsalveti @mike-scott - this thing is starting to bit rot. we may want to sit down next week and discuss

@dagriego @doanac @mike-scott let's use the eng chat meeting to discuss this one, and see what else we might want to add here.

**Comment by kprosise** [comment]
@doanac Checking in on the status of this document, should this be revived?

**Pull request closed without merging**
