### PR TITLE
[WIP] Refactor improvements 3

### LINKED ISSUE #129: document the use of "[skip ci]" tag in the last commit of a push
This stops the builders from generating a new build for this push

### PR DESCRIPTION
**Pull request by MatthewCroughan**
Fixes #129 via 9821f4d

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 30c72d95e95a1362e5c5db2e8a20c7bf7ec73fae are browesable at: https://ci.foundries.io/projects/fio-docs/builds/666/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 5e1be8e7f37219f7f6c8ad258895e4712a9408be are browesable at: https://ci.foundries.io/projects/fio-docs/builds/668/docs/artifacts/html/index.html

**Comment by MatthewCroughan** [comment]
9821f4d fixes #129

**Comment by doanac** [comment]
Docs for 0d123f18595b8c311dfe000fa89c90f5c0bf28b8 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/669/docs/artifacts/html/index.html

**Comment by MatthewCroughan** [comment]
ci-retest

**Comment by doanac** [comment]
Docs for e8783664bf61fd7b4c53f80d0bfe2605324d1fed are browesable at: https://ci.foundries.io/projects/fio-docs/builds/673/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 7838c878c2ce7c681a44d1579aaed5e149287eca are browesable at: https://ci.foundries.io/projects/fio-docs/builds/680/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 17861f88c908390e8ace4d3c1b117dea344330d1 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/681/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 4164a2141b7a544ffde9e8aa949f4ab3f25a570c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/682/docs/artifacts/html/index.html

**Pull request merged**
