### PR TITLE
getting-started: signup guide, including factory creation

### PR DESCRIPTION
**Pull request by MatthewCroughan**
** Needs Review **

This is complete as far as I'm concerned. Though it needs comments from the team.

~~I'm initializing this PR before I do too much in one commit and would like to get continual feedback until completion and eventual merge.~~

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 4185501872bbcd44099185d204795ccfd55c3e8c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/517/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for dd3282387924218fa228ac501b231690848de9b6 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/518/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 192962640f8c0e94b6d0dc7aff7a9e0cdde86127 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/519/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for fec981491850a0a7eb9fc0b79959429ae62b0d1d are browesable at: https://ci.foundries.io/projects/fio-docs/builds/520/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 730c98dd7b2bd0a0fdcad2658d146c1f2ad846a5 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/521/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 95900925eb26a2368651b4832172a50f8f3697e5 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/525/docs/artifacts/html/index.html

**Comment by EmbeddedAndroid** [comment]
lgtm, thanks @MatthewCroughan!

**Pull request merged**
