### PR TITLE
secure-boot: update secure signing instructions

### PR DESCRIPTION
**Pull request by mike-scott**
- We now use sign-file.sh which greatly simplifies signing process
- Add instructions for signing M4 binary

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for a56dd3963335fa2ae934621b39eab9b4a161b0ea are browesable at: https://ci.foundries.io/projects/fio-docs/builds/376/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 1b68cda3559e35f2e5ff95fe1324238bc2d8b4c8 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/377/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 83ad7f3ce515b7817961c6b74edba474e7decb0c are browesable at: https://ci.foundries.io/projects/fio-docs/builds/378/docs/artifacts/html/index.html

**Comment by mike-scott** [comment]
Ok this should be good enough to review

**Comment by doanac** [comment]
Docs for 4cb8d11182096f4d6b714abd8aafafea699bd08e are browesable at: https://ci.foundries.io/projects/fio-docs/builds/379/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 3c475a9b809050609c1acfd2bedc83af7a0851dd are browesable at: https://ci.foundries.io/projects/fio-docs/builds/380/docs/artifacts/html/index.html

**Pull request merged**
