### PR TITLE
rm: troubleshoot: faq: add steps to set a static ip for the board

### PR DESCRIPTION
**Pull request by vanmaegima**
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for a27e18c10d3df3878ab6e55fdaf2f04961592a31 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1332/docs/artifacts/html/index.html

**Review by kprosise — APPROVED** [review]
LGTM, as far as grammar and style go.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by kprosise** [comment]
I am going to go ahead and merge.

**Pull request merged**
