### PR TITLE
Add mention of credit card to billing

### PR DESCRIPTION
**Pull request by kprosise**
Changing credit card used was mentioned under payment and billing on the subscription and billing page. As changing the card used is a frequent request, the hope is that by explicitly adding "credit card" it will be more likely to come up during a search of the docs.

QA Steps: Linter, linkcheck, and viewed rendered html. No issues to report.

This commit addresses FFTK-2734  
This commit applies to FFTK-2729

## Readiness

*   [x] Merge (pending reviews)
*   [ ] Merge after _date or event_
*   [ ] Draft

## Overview

_Very small addition. Adds mention of "credit card" to increase findability of info_

## Checklist

_Optional. Add a 'x' to steps taken._  
_You can fill this out after opening the PR. "Did I..."_

*   [x] Run spelling and grammar check, preferably with linter.
*   [x] Avoid changing any header associated with a link/reference.
*   [ ] Step through instructions (or ask someone to do so).
*   [x] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
*   [x] Match tone and style of page/section.
*   [x] Run `make linkcheck`.
*   [x] View HTML in a browser to check rendering.
*   [x] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
*   [x] follow best practices for commits.
    *   [x] Descriptive title written in the imperative.
    *   [x] Include brief overview of QA steps taken.
    *   [x] Mention any related issues numbers.
    *   [x] End message with sign off/DCO line (`-s, --signoff`).
    *   [x] Sign commit with your gpg key (`-S, --gpg-sign`).
    *   [x] Squash commits if needed.
*   [x] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._  
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for f409400646c2b363ca81fa03c2ad2544881afe3a are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2330/docs/artifacts/html/index.html

**Review by MiloCasagrande — COMMENTED** [review]
One minor thing I would add as well: they can change the billing address as well (always in the same place where they can change/update the credit card).

**Comment by doanac** [comment]
Docs for 29b70a6be7d9431bf5031ecaea09dfeac00f4b57 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2331/docs/artifacts/html/index.html

**Review by MiloCasagrande — APPROVED** [review]
LGTM.

**Pull request merged**
