### PR TITLE
ug: custom-ci: Switch to usage of the new compose publish utility

### PR DESCRIPTION
**Pull request by mike-sul**
Replace references to `compose-publish` utility with references to `composectl publish` utility since we moved all App related functionality into the single component `composectl` and will be doing further development only in the scope of `composeapp` project.

# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

* [x] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for ea6805f927d90020eb8a97d279b5811f44e5cf94 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2788/docs/artifacts/html/index.html

**Comment by mike-sul** [comment]
@vanmaegima @caiotpereira Updating the doc on the custom Ci for Apps so it references the `composectl publish` instead of `compose-publish`. [The gihub workflow example](https://github.com/foundriesio/custom-ci-app/blob/custom-ci-devel/.github/workflows/fio-app-ci.yml) was updated too.

**Review by vanmaegima — APPROVED** [review]

**Comment by mike-sul** [comment]
@kprosise It looks like the test/vale failure is not related to this PR change.

**Review by kprosise — APPROVED** [review]
LGTM!

**Pull request merged**
