### PR TITLE
add imx8mp information and general improvements

### PR DESCRIPTION
**Pull request by vanmaegima**

### CODE REVIEW

**Comment by mwasilew** [comment]
LGTM

**Review by angolini — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Comment by mike-scott** [comment]
Hm.. broken link reports:
Not Found for url: https://github.com/foundriesio/meta-lmp/blob/master/meta-lmp-bsp/dynamic-layers/xilinx-tools/recipes-bsp/bitstream/bitstream-signed_git.bb
Looks like a valid missing link

**Comment by ricardosalveti** [comment]
Yeah, it was recently renamed to https://github.com/foundriesio/meta-lmp/blob/master/meta-lmp-bsp/dynamic-layers/xilinx-tools/recipes-bsp/bitstream/bitstream-signed.bb, so we need to fix the link as well.

**Comment by doanac** [comment]
Docs for 315befa89eab8dd47ec7536d0501140ccb639e47 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/1262/docs/artifacts/html/index.html

**Comment by vanmaegima** [comment]
@mike-scott @ricardosalveti thanks, the link was fixed in another PR (already merged to master)

**Review by kprosise — APPROVED** [review]
LGTM!

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by kprosise** [comment]
Everything looks good, merging PR.

**Pull request merged**
