### PR TITLE
rm: Add details for Google Artifact Registry

### PR DESCRIPTION
**Pull request by doanac**
Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
@kprosise @mike-sul - I'm still investigating what's possible for the device side use of GAR. It will wind up either having a blurb like we do for AWS or Azure - just have to confirm what's possible

**Comment by doanac** [comment]
Docs for 46465b8d79d2904afb88dbc699e308bf427a3451 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1433/docs/artifacts/html/index.html

**Comment by doanac** [comment]
I'm hedging my bets here - I have a support question with GCP, but I think this is going to be our answer for device access.

**Comment by doanac** [comment]
Docs for 38bbad8387a36f05235b8c3af3bc0a0b1cc5e00e are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1434/docs/artifacts/html/index.html

**Review by kprosise — APPROVED** [review]
LGTM

**Review by mike-scott — APPROVED** [review]
LGTM

**Comment by doanac** [comment]
@kprosise - i ran the steps outlined in this document in andy-corp to product this build - https://app.foundries.io/factories/andy-corp/targets/204/artifacts/build-amd64-partner/console.log

**Comment by kprosise** [comment]
@doanac you can merge when ready!

**Pull request merged**
