### PR TITLE
security: secure boot on imx

### PR DESCRIPTION
**Pull request by ldts**
Succintly describe the yocto configuration and boot on imx8mm

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 03a5638e1ba35e7ee8536189aa8f807809a0fcce are browesable at: https://ci.foundries.io/projects/fio-docs/builds/712/docs/artifacts/html/index.html

**Comment by MatthewCroughan** [comment]
@ldts If you could rebase this on master after I've merged #138, or just rebase it on that branch, that will fix the link error, since it has been fixed in that PR.

**Comment by MatthewCroughan** [comment]
I cherry picked this in #138 for convenience. cdbf33e

**Comment by ldts** [comment]
thanks @MatthewCroughan !

**Pull request closed without merging**
