### PR TITLE
userguide: Adding Working with Docker and VSCode

### PR DESCRIPTION
**Pull request by munoz0raul**

### CODE REVIEW

**Comment by dagriego** [comment]
I'm having reservations about supporting this in our documentation.  After a clean install of macOS I'm unable to get this to work.  I'm afraid that we will pulled into supporting this with every variation of VS Code/Docker/OS.  At this point I'm not sure if it will give will be worth the effort

**Comment by doanac** [comment]
> I'm having reservations about supporting this in our documentation. 

Maybe this is a blog?

**Comment by dagriego** [comment]
> > I'm having reservations about supporting this in our documentation.
> 
> Maybe this is a blog?

I think this would be a good place.

**Comment by munoz0raul** [comment]
I think we should ask someone else to give it a try on MAC and on Linux. I really like the idea of having it on our Documentation. I believe that as we start to get more customers from Partner, it could be really useful. Also, it could be just a reference on how to use it. 

Also, it worked before to you, I think we should try to understand why it is not working anymore.

**Comment by doanac** [comment]
> I think we should ask someone else to give it a try on MAC and on Linux.

The fact we are having to do this to get the PR through is the problem we'll always have. This doc will have to be re-tested for each version of the LmP, Mac OS update, windows up, linux update. If we do a blog, we can point people to it forever, but there's not an implied "we support this" stance.

**Comment by kprosise** [comment]
I've assigned this task to myself. I am currently converting it into a blog entry for the website. @munoz0raul is it okay if we close this PR?

**Pull request closed without merging**
