### PR TITLE
qemu-x86: use ovmf.secboot.qcow2 by default

### PR DESCRIPTION
**Pull request by ricardosalveti**
Prefer the ovmf.secboot.qcow2 firmware by default as that allows
enabling and using UEFI Secure Boot.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

Prefer the ovmf.secboot.qcow2 firmware by default as that allows enabling and using UEFI Secure Boot.

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [x] Run spelling and grammar check, preferably with linter.
* [x] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [x] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [x] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [x] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [x] Request PR review by a technical writer and at least one peer.

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 1db71b92c05b3d2ac88232e6d3e9e318ebf3605a are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1476/docs/artifacts/html/index.html

**Review by Tim-Anderson — COMMENTED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]

**Review by MrCry0 — APPROVED** [review]

**Review by quaresmajose — APPROVED** [review]

**Review by kprosise — COMMENTED** [review]
LGTM.

**Review by kprosise — APPROVED** [review]

**Review by vanmaegima — APPROVED** [review]
LGTM

**Pull request merged**
