### PR TITLE
Clarify recommend statements

### PR DESCRIPTION
**Pull request by kprosise**
Instances where the documentation stated something was or was not recommended, and not following the recommends fall outside of support, were clarified to state a lack of support.

QA Steps: rendered and quickly checked html output

No issues to link

## Readiness

*   [x] Merge (pending reviews)
*   [ ] Merge after _date or event_
*   [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._  
_You can fill this out after opening the PR. "Did I..."_

*   [ ] Run spelling and grammar check, preferably with linter.
*   [x] Avoid changing any header associated with a link/reference.
*   [ ] Step through instructions (or ask someone to do so).
*   [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
*   [x] Match tone and style of page/section.
*   [x] Run `make linkcheck`.
*   [x] View HTML in a browser to check rendering.
*   [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
*   [x] follow best practices for commits.
    *   [x] Descriptive title written in the imperative.
    *   [x] Include brief overview of QA steps taken.
    *   [x] Mention any related issues numbers.
    *   [x] End message with sign off/DCO line (`-s, --signoff`).
    *   [x] Sign commit with your gpg key (`-S, --gpg-sign`).
    *   [x] Squash commits if needed.
*   [x] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._  
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 4bf4dbbd3679f1f24afa68baa4cb1807691c02b9 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2492/docs/artifacts/html/index.html

**Review by angolini — APPROVED** [review]
LGTM

**Review by vanmaegima — APPROVED** [review]

**Comment by vanmaegima** [comment]
maybe do the same for "we do not suggest"

**Comment by kprosise** [comment]
> maybe do the same for "we do not suggest"

Good one. Perhaps I will glance at a Thesaurus to see if any other similar phrases return results as well.

**Pull request merged**
