### PR TITLE
boards: imx8mm: update flash instructions

### PR DESCRIPTION
**Pull request by igoropaniuk**
Update flash instructions for i.MX 8M Mini EVK.

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for cd8f71a385dfedefb3585fc18bf67cb64b4970f2 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/804/docs/artifacts/html/index.html

**Review by ricardosalveti — APPROVED** [review]
LGTM, thanks!

**Comment by ricardosalveti** [comment]
ci-retest

**Comment by doanac** [comment]
Docs for cd8f71a385dfedefb3585fc18bf67cb64b4970f2 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/805/docs/artifacts/html/index.html

**Pull request merged**
