### PR TITLE
Sync information about container preloading

### PR DESCRIPTION
**Pull request by vanmaegima**
We have RM and UG pages about container preloading and information can get out of sync, so review and improve both pages.

Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

_Optional. Add a 'x' to steps taken._
_You can fill this out after opening the PR. "Did I..."_

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by vanmaegima** [comment]
My first thought was to drop one of the pages and leave just one on this subject, but I couldn't decide which one to remove as both have its purposes. But I would appreciate any feedback as this can cause us trouble in the future (critical information can get out of sync).

**Comment by vanmaegima** [comment]
Personally I like the RM page better, I would like to keep the information centered there, but some customers might benefit from the UG format.

**Comment by doanac** [comment]
Docs for adcb32b2625af8c6a255d56c94e0c4c796f530d2 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/1880/docs/artifacts/html/index.html

**Review by angolini — APPROVED** [review]

**Review by kprosise — APPROVED** [review]
LGTM

**Pull request merged**
