### PR TITLE
doc: delete all occurrence of trailing whitespaces/tabs

### PR DESCRIPTION
**Pull request by igoropaniuk**
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 84c25a5ce047a79f6eedc66a9405097cb296a667 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/806/docs/artifacts/html/index.html

**Comment by igoropaniuk** [comment]
ci-retest

**Comment by doanac** [comment]
Docs for 84ac64ac097931f781ef0d50a3ce4d7a28fb40d7 are browesable at: https://ci.foundries.io/projects/fio-docs/builds/808/docs/artifacts/html/index.html

**Review by ricardosalveti — APPROVED** [review]

**Review by MatthewCroughan — APPROVED** [review]
Brilliant, how did you do this? I'd like to add it to the CI process. My method would probably be sed.

**Pull request merged**
