### PR TITLE
rm: security: add UEFI PXE provisioning clarification

### PR DESCRIPTION
**Pull request by ldts**
When using QEMU to do UEFI PXE provisioning, declaring the boot order is necessary when booting the Secure Image.

This avoids entering the UEFI Shell.

With this commit we hope to avoid CS questions on the matter.

# PR Template and Checklist

Please complete as much as possible to speed up the reviewing process.

Readiness and adding reviewers as appropriate is required.

All PRs should be reviewed by a technical writer/documentation team and a peer.
If effecting customers—which is a majority of content changes—a member of Customer Success must also review.

## Readiness

* [x] Merge (pending reviews)
* [ ] Merge after _date or event_
* [ ] Draft

## Overview

_Why merge this PR? What does it solve?_

## Checklist

* [ ] Run spelling and grammar check, preferably with linter.
* [ ] Avoid changing any header associated with a link/reference.
* [ ] Step through instructions (or ask someone to do so).
* [ ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [ ] Match tone and style of page/section.
* [ ] Run `make linkcheck`.
* [ ] View HTML in a browser to check rendering.
* [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
* [ ] follow best practices for commits.
  * [ ] Descriptive title written in the imperative.
  * [ ] Include brief overview of QA steps taken.
  * [ ] Mention any related issues numbers.
  * [ ] End message with sign off/DCO line (`-s, --signoff`).
  * [ ] Sign commit with your gpg key (`-S, --gpg-sign`).
  * [ ] Squash commits if needed.
* [ ] Request PR review by a technical writer and at least one peer.

## Comments

_Any thing else that a maintainer/reviewer should know._
_This could include potential issues, rational for approach, etc._

### CODE REVIEW

**Comment by doanac** [comment]
Docs for 12de976bd6ed7e27d045df788b68fab78f4fa2ac are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2760/docs/artifacts/html/index.html

**Comment by ldts** [comment]
@kprosise can we merge?

**Review by kprosise — APPROVED** [review]
LGTM, we should get another review or two before merging.

**Comment by doanac** [comment]
Docs for d04e09b3c1c8e4de158905c51acf0ea9cca87859 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2762/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for daf9dba97883fd463987a57355e87d1456b715e3 are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2763/docs/artifacts/html/index.html

**Comment by doanac** [comment]
Docs for 418372ab45d8bc6b54cbbb34ec468cc33636ec4a are browsable at: https://ci.foundries.io/projects/fio-docs/builds/2766/docs/artifacts/html/index.html

**Review by vanmaegima — APPROVED** [review]
LGTM

**Pull request merged**
